//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoRegister.ApplicationCore.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationPageRegistrationType : MustHaveProjectEntity
    {
        public int Id { get; set; }
        public int RegistrationPageId { get; set; }
        public int RegistrationTypeId { get; set; }
    
    	/// <summary>
    	/// RelationshipName: FK_RegistrationPageRegistrationType_RegistrationPage
    	/// </summary>
        public virtual RegistrationPage RegistrationPage { get; set; }
    	/// <summary>
    	/// RelationshipName: FK_RegistrationPageRegistrationType_RegistrationType
    	/// </summary>
        public virtual RegistrationType RegistrationType { get; set; }
    }
}
