//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoRegister.ApplicationCore.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RegistrationPage : MustHaveProjectEntity
    {
        public RegistrationPage()
        {
            this.Fields = new HashSet<Field>();
            this.RegistrationPageRegistrationTypes = new HashSet<RegistrationPageRegistrationType>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
        public bool IsInternalOnly { get; set; }
        public bool IsVisible { get; set; }
        public int FormId { get; set; }

        public virtual Form Form { get; set; }
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<RegistrationPageRegistrationType> RegistrationPageRegistrationTypes { get; set; }


        [NotMapped]
        public string TempId { get; private set; }
        public void SetTempId(string id)
        {
            TempId = id;
        }

        public string GetRenderId()
        {
            return Id == 0 ? TempId : Id.ToString();
        }
    }
}
