using Microsoft.EntityFrameworkCore.Migrations;

namespace GoRegister.Migrations
{
    public partial class Countries : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "CountryId",
                table: "UserFieldResponse",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "Country",
                columns: table => new
                {
                    ISO = table.Column<string>(maxLength: 2, nullable: false),
                    Name = table.Column<string>(nullable: false),
                    ISO3 = table.Column<string>(maxLength: 3, nullable: false),
                    Numeric = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Country", x => x.ISO);
                });

            migrationBuilder.InsertData(
                table: "Country",
                columns: new[] { "ISO", "ISO3", "Name", "Numeric" },
                values: new object[,]
                {
                    { "AD", "AND", "Andorra", 20 },
                    { "MZ", "MOZ", "Mozambique", 508 },
                    { "NA", "NAM", "Namibia", 516 },
                    { "NC", "NCL", "New Caledonia", 540 },
                    { "NE", "NER", "Niger", 562 },
                    { "NF", "NFK", "Norfolk Island", 574 },
                    { "NG", "NGA", "Nigeria", 566 },
                    { "NI", "NIC", "Nicaragua", 558 },
                    { "NL", "NLD", "Netherlands", 528 },
                    { "NO", "NOR", "Norway", 578 },
                    { "NP", "NPL", "Nepal", 524 },
                    { "NR", "NRU", "Nauru", 520 },
                    { "NU", "NIU", "Niue", 570 },
                    { "NZ", "NZL", "New Zealand", 554 },
                    { "OM", "OMN", "Oman", 512 },
                    { "PA", "PAN", "Panama", 591 },
                    { "PE", "PER", "Peru", 604 },
                    { "PF", "PYF", "French Polynesia", 258 },
                    { "PG", "PNG", "Papua New Guinea", 598 },
                    { "PH", "PHL", "Philippines", 608 },
                    { "PK", "PAK", "Pakistan", 586 },
                    { "PL", "POL", "Poland", 616 },
                    { "PM", "SPM", "Saint Pierre and Miquelon", 666 },
                    { "PN", "PCN", "Pitcairn", 612 },
                    { "PR", "PRI", "Puerto Rico", 630 },
                    { "PS", "PSE", "Palestine, State of", 275 },
                    { "PT", "PRT", "Portugal", 620 },
                    { "PW", "PLW", "Palau", 585 },
                    { "MY", "MYS", "Malaysia", 458 },
                    { "PY", "PRY", "Paraguay", 600 },
                    { "MX", "MEX", "Mexico", 484 },
                    { "MV", "MDV", "Maldives", 462 },
                    { "LC", "LCA", "Saint Lucia", 662 },
                    { "LI", "LIE", "Liechtenstein", 438 },
                    { "LK", "LKA", "Sri Lanka", 144 },
                    { "LR", "LBR", "Liberia", 430 },
                    { "LS", "LSO", "Lesotho", 426 },
                    { "LT", "LTU", "Lithuania", 440 },
                    { "LU", "LUX", "Luxembourg", 442 },
                    { "LV", "LVA", "Latvia", 428 },
                    { "LY", "LBY", "Libya", 434 },
                    { "MA", "MAR", "Morocco", 504 },
                    { "MC", "MCO", "Monaco", 492 },
                    { "MD", "MDA", "Moldova, Republic of", 498 },
                    { "ME", "MNE", "Montenegro", 499 },
                    { "MF", "MAF", "Saint Martin (French part)", 663 },
                    { "MG", "MDG", "Madagascar", 450 },
                    { "MH", "MHL", "Marshall Islands", 584 },
                    { "MK", "MKD", "Republic of North Macedonia", 807 },
                    { "ML", "MLI", "Mali", 466 },
                    { "MM", "MMR", "Myanmar", 104 },
                    { "MN", "MNG", "Mongolia", 496 },
                    { "MO", "MAC", "Macao", 446 },
                    { "MP", "MNP", "Northern Mariana Islands", 580 },
                    { "MQ", "MTQ", "Martinique", 474 },
                    { "MR", "MRT", "Mauritania", 478 },
                    { "MS", "MSR", "Montserrat", 500 },
                    { "MT", "MLT", "Malta", 470 },
                    { "MU", "MUS", "Mauritius", 480 },
                    { "MW", "MWI", "Malawi", 454 },
                    { "QA", "QAT", "Qatar", 634 },
                    { "RE", "REU", "Reunion", 638 },
                    { "RO", "ROU", "Romania", 642 },
                    { "TM", "TKM", "Turkmenistan", 795 },
                    { "TN", "TUN", "Tunisia", 788 },
                    { "TO", "TON", "Tonga", 776 },
                    { "TR", "TUR", "Turkey", 792 },
                    { "TT", "TTO", "Trinidad and Tobago", 780 },
                    { "TV", "TUV", "Tuvalu", 798 },
                    { "TW", "TWN", "Taiwan (Province of China)", 158 },
                    { "TZ", "TZA", "Tanzania, the United Republic of", 834 },
                    { "UA", "UKR", "Ukraine", 804 },
                    { "UG", "UGA", "Uganda", 800 },
                    { "UM", "UMI", "United States Minor Outlying Islands", 581 },
                    { "US", "USA", "United States", 840 },
                    { "UY", "URY", "Uruguay", 858 },
                    { "UZ", "UZB", "Uzbekistan", 860 },
                    { "VA", "VAT", "Holy See (Vatican City State)", 336 },
                    { "VC", "VCT", "Saint Vincent and the Grenadines", 670 },
                    { "VE", "VEN", "Venezuela", 862 },
                    { "VG", "VGB", "Virgin Islands (British)", 92 },
                    { "VI", "VIR", "Virgin Islands (U.S.)", 850 },
                    { "VN", "VNM", "Viet Nam", 704 },
                    { "VU", "VUT", "Vanuatu", 548 },
                    { "WF", "WLF", "Wallis and Futuna", 876 },
                    { "WS", "WSM", "Samoa", 882 },
                    { "YE", "YEM", "Yemen", 887 },
                    { "YT", "MYT", "Mayotte", 175 },
                    { "ZA", "ZAF", "South Africa", 710 },
                    { "ZM", "ZMB", "Zambia", 894 },
                    { "TL", "TLS", "Timor-Leste", 626 },
                    { "TK", "TKL", "Tokelau", 772 },
                    { "TJ", "TJK", "Tajikistan", 762 },
                    { "TH", "THA", "Thailand", 764 },
                    { "RS", "SRB", "Serbia", 688 },
                    { "RU", "RUS", "Russian Federation", 643 },
                    { "RW", "RWA", "Rwanda", 646 },
                    { "SA", "SAU", "Saudi Arabia", 682 },
                    { "SB", "SLB", "Solomon Islands", 90 },
                    { "SC", "SYC", "Seychelles", 690 },
                    { "SD", "SDN", "Sudan", 736 },
                    { "SE", "SWE", "Sweden", 752 },
                    { "SG", "SGP", "Singapore", 702 },
                    { "SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", 654 },
                    { "SI", "SVN", "Slovenia", 705 },
                    { "SJ", "SJM", "Svalbard and Jan Mayen", 744 },
                    { "SK", "SVK", "Slovakia", 703 },
                    { "LB", "LBN", "Lebanon", 422 },
                    { "SL", "SLE", "Sierra Leone", 694 },
                    { "SN", "SEN", "Senegal", 686 },
                    { "SO", "SOM", "Somalia", 706 },
                    { "SR", "SUR", "Suriname", 740 },
                    { "SS", "SSD", "South Sudan", 728 },
                    { "ST", "STP", "Sao Tome and Principe", 678 },
                    { "SV", "SLV", "El Salvador", 222 },
                    { "SX", "SXM", "Sint Maarten (Dutch part)", 534 },
                    { "SY", "SYR", "Syrian Arab Republic (the)", 760 },
                    { "SZ", "SWZ", "Swaziland", 748 },
                    { "TC", "TCA", "Turks and Caicos Islands", 796 },
                    { "TD", "TCD", "Chad", 148 },
                    { "TF", "ATF", "French Southern Territories", 260 },
                    { "TG", "TGO", "Togo", 768 },
                    { "SM", "SMR", "San Marino", 674 },
                    { "LA", "LAO", "Lao People's Democratic Republic", 418 },
                    { "KZ", "KAZ", "Kazakhstan", 398 },
                    { "KY", "CYM", "Cayman Islands", 136 },
                    { "BV", "BVT", "Bouvet Island", 74 },
                    { "BW", "BWA", "Botswana", 72 },
                    { "BY", "BLR", "Belarus", 112 },
                    { "BZ", "BLZ", "Belize", 84 },
                    { "CA", "CAN", "Canada", 124 },
                    { "CC", "CCK", "Cocos (Keeling) Islands", 166 },
                    { "CD", "COD", "Congo, the Democratic Republic of the", 180 },
                    { "CF", "CAF", "Central African Republic", 140 },
                    { "CG", "COG", "Congo", 178 },
                    { "CH", "CHE", "Switzerland", 756 },
                    { "CI", "CIV", "Cote D'Ivoire", 384 },
                    { "CK", "COK", "Cook Islands", 184 },
                    { "CL", "CHL", "Chile", 152 },
                    { "CM", "CMR", "Cameroon", 120 },
                    { "CN", "CHN", "China", 156 },
                    { "CO", "COL", "Colombia", 170 },
                    { "CR", "CRI", "Costa Rica", 188 },
                    { "CU", "CUB", "Cuba", 192 },
                    { "CV", "CPV", "Cape Verde", 132 },
                    { "CW", "CUW", "Curaçao", 531 },
                    { "CX", "CXR", "Christmas Island", 162 },
                    { "CY", "CYP", "Cyprus", 196 },
                    { "CZ", "CZE", "Czech Republic", 203 },
                    { "DE", "DEU", "Germany", 276 },
                    { "DJ", "DJI", "Djibouti", 262 },
                    { "DK", "DNK", "Denmark", 208 },
                    { "DM", "DMA", "Dominica", 212 },
                    { "BT", "BTN", "Bhutan", 64 },
                    { "BS", "BHS", "Bahamas", 44 },
                    { "BR", "BRA", "Brazil", 76 },
                    { "BQ", "BES", "Bonaire, Sint Eustatius and Saba", 535 },
                    { "AE", "ARE", "United Arab Emirates", 784 },
                    { "AF", "AFG", "Afghanistan", 4 },
                    { "AG", "ATG", "Antigua and Barbuda", 28 },
                    { "AI", "AIA", "Anguilla", 660 },
                    { "AL", "ALB", "Albania", 8 },
                    { "AM", "ARM", "Armenia", 51 },
                    { "AO", "AGO", "Angola", 24 },
                    { "AQ", "ATA", "Antarctica", 10 },
                    { "AR", "ARG", "Argentina", 32 },
                    { "AS", "ASM", "American Samoa", 16 },
                    { "AT", "AUT", "Austria", 40 },
                    { "AU", "AUS", "Australia", 36 },
                    { "AW", "ABW", "Aruba", 533 },
                    { "DO", "DOM", "Dominican Republic", 214 },
                    { "AX", "ALA", "Åland Islands", 248 },
                    { "BA", "BIH", "Bosnia and Herzegovina", 70 },
                    { "BB", "BRB", "Barbados", 52 },
                    { "BD", "BGD", "Bangladesh", 50 },
                    { "BE", "BEL", "Belgium", 56 },
                    { "BF", "BFA", "Burkina Faso", 854 },
                    { "BG", "BGR", "Bulgaria", 100 },
                    { "BH", "BHR", "Bahrain", 48 },
                    { "BI", "BDI", "Burundi", 108 },
                    { "BJ", "BEN", "Benin", 204 },
                    { "BL", "BLM", "Saint Barthélemy", 652 },
                    { "BM", "BMU", "Bermuda", 60 },
                    { "BN", "BRN", "Brunei Darussalam", 96 },
                    { "BO", "BOL", "Bolivia", 68 },
                    { "AZ", "AZE", "Azerbaijan", 31 },
                    { "ZW", "ZWE", "Zimbabwe", 716 },
                    { "DZ", "DZA", "Algeria", 12 },
                    { "EE", "EST", "Estonia", 233 },
                    { "HN", "HND", "Honduras", 340 },
                    { "HR", "HRV", "Croatia", 191 },
                    { "HT", "HTI", "Haiti", 332 },
                    { "HU", "HUN", "Hungary", 348 },
                    { "ID", "IDN", "Indonesia", 360 },
                    { "IE", "IRL", "Ireland", 372 },
                    { "IL", "ISR", "Israel", 376 },
                    { "IM", "IMN", "Isle of Man", 833 },
                    { "IN", "IND", "India", 356 },
                    { "IO", "IOT", "British Indian Ocean Territory", 86 },
                    { "IQ", "IRQ", "Iraq", 368 },
                    { "IR", "IRN", "Iran, Islamic Republic of", 364 },
                    { "IS", "ISL", "Iceland", 352 },
                    { "IT", "ITA", "Italy", 380 },
                    { "JE", "JEY", "Jersey", 832 },
                    { "JM", "JAM", "Jamaica", 388 },
                    { "JO", "JOR", "Jordan", 400 },
                    { "JP", "JPN", "Japan", 392 },
                    { "KE", "KEN", "Kenya", 404 },
                    { "KG", "KGZ", "Kyrgyzstan", 417 },
                    { "KH", "KHM", "Cambodia", 116 },
                    { "KI", "KIR", "Kiribati", 296 },
                    { "KM", "COM", "Comoros", 174 },
                    { "KN", "KNA", "Saint Kitts and Nevis", 659 },
                    { "KP", "PRK", "Korea, Democratic People's Republic of", 408 },
                    { "KR", "KOR", "Korea, Republic of", 410 },
                    { "KW", "KWT", "Kuwait", 414 },
                    { "HM", "HMD", "Heard Island and Mcdonald Islands", 334 },
                    { "HK", "HKG", "Hong Kong", 344 },
                    { "GY", "GUY", "Guyana", 328 },
                    { "GW", "GNB", "Guinea-Bissau", 624 },
                    { "EG", "EGY", "Egypt", 818 },
                    { "EH", "ESH", "Western Sahara", 732 },
                    { "ER", "ERI", "Eritrea", 232 },
                    { "ES", "ESP", "Spain", 724 },
                    { "ET", "ETH", "Ethiopia", 231 },
                    { "FI", "FIN", "Finland", 246 },
                    { "FJ", "FJI", "Fiji", 242 },
                    { "FK", "FLK", "Falkland Islands (Malvinas)", 238 },
                    { "FM", "FSM", "Micronesia, Federated States of", 583 },
                    { "FO", "FRO", "Faroe Islands", 234 },
                    { "FR", "FRA", "France", 250 },
                    { "GA", "GAB", "Gabon", 266 },
                    { "GB", "GBR", "United Kingdom", 826 },
                    { "EC", "ECU", "Ecuador", 218 },
                    { "GD", "GRD", "Grenada", 308 },
                    { "GF", "GUF", "French Guiana", 254 },
                    { "GG", "GGY", "Guernsey", 831 },
                    { "GH", "GHA", "Ghana", 288 },
                    { "GI", "GIB", "Gibraltar", 292 },
                    { "GL", "GRL", "Greenland", 304 },
                    { "GM", "GMB", "Gambia", 270 },
                    { "GN", "GIN", "Guinea", 324 },
                    { "GP", "GLP", "Guadeloupe", 312 },
                    { "GQ", "GNQ", "Equatorial Guinea", 226 },
                    { "GR", "GRC", "Greece", 300 },
                    { "GS", "SGS", "South Georgia and the South Sandwich Islands", 239 },
                    { "GT", "GTM", "Guatemala", 320 },
                    { "GU", "GUM", "Guam", 316 },
                    { "GE", "GEO", "Georgia", 268 }
                });

            migrationBuilder.UpdateData(
                table: "User",
                keyColumn: "Id",
                keyValue: 1,
                column: "PasswordHash",
                value: "AQAAAAEAACcQAAAAEC6LEzY71UIPa+JAGqRyELxK5LgVkwx3TAFbxMrzcwk/KY7OoPZ+Y4hHE9t2D0w7Tg==");

            migrationBuilder.CreateIndex(
                name: "IX_UserFieldResponse_CountryId",
                table: "UserFieldResponse",
                column: "CountryId");

            migrationBuilder.AddForeignKey(
                name: "FK_UserFieldResponse_Country_CountryId",
                table: "UserFieldResponse",
                column: "CountryId",
                principalTable: "Country",
                principalColumn: "ISO",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserFieldResponse_Country_CountryId",
                table: "UserFieldResponse");

            migrationBuilder.DropTable(
                name: "Country");

            migrationBuilder.DropIndex(
                name: "IX_UserFieldResponse_CountryId",
                table: "UserFieldResponse");

            migrationBuilder.DropColumn(
                name: "CountryId",
                table: "UserFieldResponse");

            migrationBuilder.UpdateData(
                table: "User",
                keyColumn: "Id",
                keyValue: 1,
                column: "PasswordHash",
                value: "AQAAAAEAACcQAAAAEIKOFqiO4Y9dk/wLvG1+MQ/005ovDnPgJh7oJggxAhF59jXnkCMNSdYmUILxsTOATw==");
        }
    }
}
