// <auto-generated />
using System;
using GoRegister.ApplicationCore.Data;
using GoRegister.ApplicationCore.Data.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoRegister.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200609114705_AddCustomPageAuditTables")]
    partial class AddCustomPageAuditTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoRegister.Data.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("DateFormat");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<int?>("ProjectId");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("TimeZone");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("ProjectId");

                    b.HasIndex("NormalizedUserName", "ProjectId")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL AND [ProjectId] IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e66572a8-1aa6-4665-a91c-eee307976b67",
                            Email = "WEBMASTER@BANKS-SADLER.COM",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "WEBMASTER@BANKS-SADLER.COM",
                            NormalizedUserName = "WEBMASTER@BANKS-SADLER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEND2zxE7GNC36jrEG7fInSv77w7wHElRMjUxLMqlH4VCxlsNO7xJDO2QCfwDeRjBFw==",
                            PhoneNumberConfirmed = false,
                            ProjectId = 1,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "WEBMASTER@BANKS-SADLER.COM"
                        });
                });

            modelBuilder.Entity("GoRegister.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("ProjectId");

                    b.Property<string>("Slug");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CustomPage");
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPageAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PageStatus");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("CustomPageAudit");
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPageAuditRegistrationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomPageAuditId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CustomPageAuditId");

                    b.ToTable("CustomPageAuditRegistrationType");
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPageRegistrationStatus", b =>
                {
                    b.Property<int>("CustomPageId");

                    b.Property<int>("RegistrationStatusId");

                    b.HasKey("CustomPageId", "RegistrationStatusId");

                    b.HasIndex("RegistrationStatusId");

                    b.ToTable("CustomPageRegistrationStatus");
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPageRegistrationType", b =>
                {
                    b.Property<int>("CustomPageId");

                    b.Property<int>("RegistrationTypeId");

                    b.HasKey("CustomPageId", "RegistrationTypeId");

                    b.HasIndex("RegistrationTypeId");

                    b.ToTable("CustomPageRegistrationType");
                });

            modelBuilder.Entity("GoRegister.Data.Models.DelegateUser", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("ParentDelegateUserId");

                    b.Property<string>("RegistrationDocument");

                    b.Property<int>("RegistrationStatusId");

                    b.Property<int>("RegistrationTypeId");

                    b.Property<Guid>("UniqueIdentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentDelegateUserId");

                    b.HasIndex("RegistrationStatusId");

                    b.HasIndex("RegistrationTypeId");

                    b.ToTable("DelegateUser");
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("BatchId");

                    b.Property<string>("Bcc");

                    b.Property<string>("Body");

                    b.Property<string>("Cc");

                    b.Property<int>("DelegateUserId");

                    b.Property<int?>("EmailTemplateId");

                    b.Property<string>("FromEmail");

                    b.Property<string>("FromEmailDisplayName");

                    b.Property<int?>("StatusId");

                    b.Property<string>("Subject");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.HasIndex("DelegateUserId");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailAudit");
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailAuditBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("BatchId");

                    b.Property<DateTime>("DateSent");

                    b.Property<int>("EmailSentCount");

                    b.Property<string>("EmailType");

                    b.Property<int>("ProjectId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmailAuditBatch");
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailAuditNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AsmGroupId");

                    b.Property<string>("Attempt");

                    b.Property<string>("Category");

                    b.Property<string>("Email");

                    b.Property<int>("EmailAuditId");

                    b.Property<string>("EventType");

                    b.Property<string>("Ip");

                    b.Property<string>("Reason");

                    b.Property<string>("Response");

                    b.Property<string>("SgEventId");

                    b.Property<string>("SgMessageId");

                    b.Property<string>("SmtpId");

                    b.Property<string>("Status");

                    b.Property<DateTime>("Timestamp");

                    b.Property<bool>("Tls");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.Property<string>("UserAgent");

                    b.HasKey("Id");

                    b.HasIndex("EmailAuditId");

                    b.ToTable("EmailAuditNotification");
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bcc");

                    b.Property<string>("Body");

                    b.Property<string>("Cc");

                    b.Property<int>("EmailType");

                    b.Property<bool>("IsEnabled");

                    b.Property<int>("ProjectId");

                    b.Property<int>("RegistrationStatusId");

                    b.Property<int>("RegistrationTypeId");

                    b.Property<string>("Subject");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RegistrationStatusId");

                    b.HasIndex("RegistrationTypeId");

                    b.ToTable("EmailTemplate");
                });

            modelBuilder.Entity("GoRegister.Data.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiFieldName");

                    b.Property<bool>("CanModify");

                    b.Property<string>("Class");

                    b.Property<string>("CustomAttributes");

                    b.Property<string>("DataTag");

                    b.Property<string>("DefaultValue");

                    b.Property<int>("FieldTypeId");

                    b.Property<string>("HelpTextToolTip");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsMandatory");

                    b.Property<bool>("IsReadOnly");

                    b.Property<int?>("MaxLength");

                    b.Property<int?>("MinLength");

                    b.Property<string>("Name");

                    b.Property<string>("Options");

                    b.Property<string>("Placeholder");

                    b.Property<string>("PreText");

                    b.Property<int>("ProjectId");

                    b.Property<int>("RegistrationPageId");

                    b.Property<string>("ReportingHeader");

                    b.Property<int>("SortOrder");

                    b.Property<string>("SubText");

                    b.Property<Guid>("UniqueIdentifier");

                    b.HasKey("Id");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RegistrationPageId");

                    b.ToTable("Field");

                    b.HasDiscriminator<int>("FieldTypeId");
                });

            modelBuilder.Entity("GoRegister.Data.Models.FieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInformation");

                    b.Property<string>("AdditionalInformation1");

                    b.Property<string>("AdditionalInformation2");

                    b.Property<int?>("AgendaId");

                    b.Property<string>("Attributes");

                    b.Property<int?>("Capacity");

                    b.Property<string>("Class");

                    b.Property<string>("DataTag");

                    b.Property<string>("Description");

                    b.Property<int>("FieldId");

                    b.Property<string>("InternalInformation");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ProjectId");

                    b.Property<string>("ReportingTitle");

                    b.Property<int>("SortOrder");

                    b.Property<decimal?>("VisaAllowance");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ProjectId");

                    b.ToTable("FieldOption");
                });

            modelBuilder.Entity("GoRegister.Data.Models.FieldOptionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FieldId");

                    b.Property<int>("FieldOptionId");

                    b.Property<int?>("NextFieldId");

                    b.Property<int?>("NextFieldOptionId");

                    b.Property<int>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("FieldOptionId");

                    b.HasIndex("NextFieldOptionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("FieldOptionRule");
                });

            modelBuilder.Entity("GoRegister.Data.Models.FieldType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("FieldType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Textbox"
                        },
                        new
                        {
                            Id = 10,
                            Description = "PhoneNumber"
                        },
                        new
                        {
                            Id = 2,
                            Description = "RadioButton"
                        },
                        new
                        {
                            Id = 4,
                            Description = "TextArea"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Date"
                        });
                });

            modelBuilder.Entity("GoRegister.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<string>("Host");

                    b.Property<string>("Name");

                    b.Property<string>("Prefix");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Host = "localhost:5021",
                            Name = "Admin",
                            Prefix = "admin"
                        });
                });

            modelBuilder.Entity("GoRegister.Data.Models.ProjectSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArchiveDate");

                    b.Property<bool>("BlockSearchEngineIndexing");

                    b.Property<DateTime>("DeleteDataDate");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("EmailDisplayFrom");

                    b.Property<string>("EmailReplyTo");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ExternalReference");

                    b.Property<bool>("IsSitewidePasswordEnabled");

                    b.Property<string>("MetaDescription");

                    b.Property<string>("PageTitleTag");

                    b.Property<string>("ProjectResourceId");

                    b.Property<string>("SitewidePasswordHashed");

                    b.Property<string>("SitewidePasswordPlainText");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Timezone");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchiveDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BlockSearchEngineIndexing = false,
                            DeleteDataDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSitewidePasswordEnabled = false,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GoRegister.Data.Models.ProjectTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateArchived");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("FooterScripts");

                    b.Property<string>("HeadScripts");

                    b.Property<bool>("IsArchived");

                    b.Property<string>("LayoutName");

                    b.Property<string>("Name");

                    b.Property<string>("OverrideCss");

                    b.Property<int?>("ProjectId");

                    b.Property<string>("ThemeCss");

                    b.Property<Guid>("ThemeGuid");

                    b.Property<string>("ThemeVariableObject");

                    b.Property<string>("ThemeVariables");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTheme");
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsInternalOnly");

                    b.Property<int>("ProjectId");

                    b.Property<int>("SortOrder");

                    b.Property<string>("Title");

                    b.Property<Guid>("UniqueIdentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("RegistrationPage");
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationPageRegistrationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectId");

                    b.Property<int>("RegistrationPageId");

                    b.Property<int>("RegistrationTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RegistrationPageId");

                    b.HasIndex("RegistrationTypeId");

                    b.ToTable("RegistrationPageRegistrationType");
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanCancel");

                    b.Property<bool>("CanModify");

                    b.Property<string>("CancelledText");

                    b.Property<string>("ConfirmedText");

                    b.Property<DateTime?>("DateCancelTo");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModifyTo");

                    b.Property<DateTime?>("DateRegistrationFrom");

                    b.Property<DateTime?>("DateRegistrationTo");

                    b.Property<string>("DeclinedText");

                    b.Property<string>("Description");

                    b.Property<string>("InvitedText");

                    b.Property<bool>("IsTesting");

                    b.Property<string>("Name");

                    b.Property<string>("NotInvitedText");

                    b.Property<int>("ProjectId");

                    b.Property<int>("UseCreatedById");

                    b.Property<string>("WaitingText");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("RegistrationPath");
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationStatus", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("RegistrationStatus");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Not Invited"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Invited"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Declined"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cancelled"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Waiting"
                        });
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Capacity")
                        .IsRequired();

                    b.Property<DateTime>("DateCreated");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("ProjectId");

                    b.Property<int>("RegistrationPathId");

                    b.Property<int>("UserCreatedById");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RegistrationPathId");

                    b.ToTable("RegistrationType");
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationTypeField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FieldId");

                    b.Property<bool>("IsHidden");

                    b.Property<bool>("IsInternalOnly");

                    b.Property<int>("ProjectId");

                    b.Property<int>("RegistrationTypeId");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RegistrationTypeId");

                    b.ToTable("RegistrationTypeField");
                });

            modelBuilder.Entity("GoRegister.Data.Models.TenantUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<string>("DisallowedSubDomains");

                    b.Property<string>("Host");

                    b.Property<bool>("IsSubdomainHost");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TenantUrl");
                });

            modelBuilder.Entity("GoRegister.Data.Models.UserFieldResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BooleanValue");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<DateTime>("DateTimeValue");

                    b.Property<int>("FieldId");

                    b.Property<int?>("FieldOptionId");

                    b.Property<int>("NumberValue");

                    b.Property<int>("ProjectId");

                    b.Property<string>("StringValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("FieldOptionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFieldResponse");
                });

            modelBuilder.Entity("GoRegister.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "c2cfa7e4-7e0a-41ea-9999-ca1358e5ebb5",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("GoRegister.Data.Models.DateField", b =>
                {
                    b.HasBaseType("GoRegister.Data.Models.Field");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("GoRegister.Data.Models.SingleSelectField", b =>
                {
                    b.HasBaseType("GoRegister.Data.Models.Field");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("GoRegister.Data.Models.TelephoneField", b =>
                {
                    b.HasBaseType("GoRegister.Data.Models.Field");

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("GoRegister.Data.Models.TextField", b =>
                {
                    b.HasBaseType("GoRegister.Data.Models.Field");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("GoRegister.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPage", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany("CustomPages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPageAuditRegistrationType", b =>
                {
                    b.HasOne("GoRegister.Data.Models.CustomPageAudit", "CustomPageAudit")
                        .WithMany("CustomPageAuditRegistrationTypes")
                        .HasForeignKey("CustomPageAuditId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPageRegistrationStatus", b =>
                {
                    b.HasOne("GoRegister.Data.Models.CustomPage", "CustomPage")
                        .WithMany("CustomPageRegistrationStatuses")
                        .HasForeignKey("CustomPageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.RegistrationStatus", "RegistrationStatus")
                        .WithMany("CustomPageRegistrationStatuses")
                        .HasForeignKey("RegistrationStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.CustomPageRegistrationType", b =>
                {
                    b.HasOne("GoRegister.Data.Models.CustomPage", "CustomPage")
                        .WithMany("CustomPageRegistrationTypes")
                        .HasForeignKey("CustomPageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.RegistrationType", "RegistrationType")
                        .WithMany("CustomPageRegistrationTypes")
                        .HasForeignKey("RegistrationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.DelegateUser", b =>
                {
                    b.HasOne("GoRegister.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("DelegateUser")
                        .HasForeignKey("GoRegister.Data.Models.DelegateUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.DelegateUser", "ParentDelegateUser")
                        .WithMany()
                        .HasForeignKey("ParentDelegateUserId");

                    b.HasOne("GoRegister.Data.Models.RegistrationStatus", "RegistrationStatus")
                        .WithMany()
                        .HasForeignKey("RegistrationStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.RegistrationType", "RegistrationType")
                        .WithMany("DelegateUsers")
                        .HasForeignKey("RegistrationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailAudit", b =>
                {
                    b.HasOne("GoRegister.Data.Models.DelegateUser", "DelegateUser")
                        .WithMany()
                        .HasForeignKey("DelegateUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.EmailTemplate", "EmailTemplate")
                        .WithMany()
                        .HasForeignKey("EmailTemplateId");
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailAuditBatch", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailAuditNotification", b =>
                {
                    b.HasOne("GoRegister.Data.Models.EmailAudit", "EmailAudit")
                        .WithMany("EmailAuditNotifications")
                        .HasForeignKey("EmailAuditId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.EmailTemplate", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoRegister.Data.Models.RegistrationStatus", "RegistrationStatus")
                        .WithMany()
                        .HasForeignKey("RegistrationStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.RegistrationType", "RegistrationType")
                        .WithMany()
                        .HasForeignKey("RegistrationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.Field", b =>
                {
                    b.HasOne("GoRegister.Data.Models.FieldType", "FieldType")
                        .WithMany("Fields")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoRegister.Data.Models.RegistrationPage", "RegistrationPage")
                        .WithMany("Fields")
                        .HasForeignKey("RegistrationPageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.FieldOption", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Field", "Field")
                        .WithMany("FieldOptions")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GoRegister.Data.Models.FieldOptionRule", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Field", "Field")
                        .WithMany("FieldOptionRules")
                        .HasForeignKey("FieldId");

                    b.HasOne("GoRegister.Data.Models.FieldOption", "FieldOption")
                        .WithMany("FieldOptionRules")
                        .HasForeignKey("FieldOptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.FieldOption", "NextFieldOption")
                        .WithMany("NextFieldOptionRules")
                        .HasForeignKey("NextFieldOptionId");

                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GoRegister.Data.Models.Project", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("GoRegister.Data.Models.ProjectSettings", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithOne("ProjectSettings")
                        .HasForeignKey("GoRegister.Data.Models.ProjectSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.ProjectTheme", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany("ProjectThemes")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationPage", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationPageRegistrationType", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoRegister.Data.Models.RegistrationPage", "RegistrationPage")
                        .WithMany("RegistrationPageRegistrationTypes")
                        .HasForeignKey("RegistrationPageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.RegistrationType", "RegistrationType")
                        .WithMany("RegistrationPageRegistrationTypes")
                        .HasForeignKey("RegistrationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationPath", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationType", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoRegister.Data.Models.RegistrationPath", "RegistrationPath")
                        .WithMany("RegistrationTypes")
                        .HasForeignKey("RegistrationPathId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.RegistrationTypeField", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Field", "Field")
                        .WithMany("RegistrationTypeFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoRegister.Data.Models.RegistrationType", "RegistrationType")
                        .WithMany("RegistrationTypeFields")
                        .HasForeignKey("RegistrationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoRegister.Data.Models.TenantUrl", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("GoRegister.Data.Models.UserFieldResponse", b =>
                {
                    b.HasOne("GoRegister.Data.Models.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.FieldOption", "FieldOption")
                        .WithMany()
                        .HasForeignKey("FieldOptionId");

                    b.HasOne("GoRegister.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoRegister.Data.Models.DelegateUser", "DelegateUser")
                        .WithMany("UserFieldResponses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GoRegister.Data.Models.UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GoRegister.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GoRegister.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GoRegister.Data.Models.UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoRegister.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GoRegister.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
